# Generated by Django 5.2.4 on 2025-07-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myautomationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostwanted',
            name='updated_at',
        ),
    ]
